
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('SBCs').truncate()
    .then(function () {
      // Inserts seed entries
      return knex('SBCs').insert([
        {"count": "1", "City": "Anderson", "State": "SC", "Attend": "31,215", "Church": "NewSpring Community Church"}, 
        {"count": "2", "City": "Lake Forest", "State": "CA", "Attend": "24,342", "Church": "Saddleback Valley Community Church"}, 
        {"count": "3", "City": "Houston", "State": "TX", "Attend": "23,610", "Church": "Second Baptist Church"}, 
        {"count": "4", "City": "The Woodlands", "State": "TX", "Attend": "18,000", "Church": "Woodlands Church"}, 
        {"count": "5", "City": "Plano", "State": "TX", "Attend": "15,145", "Church": "Prestonwood Baptist Church"}, 
        {"count": "6", "City": "Lynchburg", "State": "VA", "Attend": "13,500", "Church": "Thomas Road Baptist Church"}, 
        {"count": "7", "City": "Flower Mound", "State": "TX", "Attend": "11,000", "Church": "The Village Church"}, 
        {"count": "8", "City": "Albuquerque", "State": "NM", "Attend": "10,557", "Church": "Sagebrush Community Church"}, 
        {"count": "9", "City": "Palmetto Bay", "State": "FL", "Attend": "9,354", "Church": "Christ Fellowship Baptist Church, Inc"}, 
        {"count": "10", "City": "Rockwall", "State": "TX", "Attend": "9,304", "Church": "Lake Pointe Church"}, 
        {"count": "11", "City": "Houston", "State": "TX", "Attend": "9,000", "Church": "The Fountain of Praise*"}, 
        {"count": "11", "City": "Porter Ranch", "State": "CA", "Attend": "9,000", "Church": "Shepherd of the Hills"}, 
        {"count": "13", "City": "Springdale", "State": "AR", "Attend": "8,978", "Church": "Cross Church"}, 
        {"count": "14", "City": "Brandon", "State": "MS", "Attend": "8,108", "Church": "Pinelake Church"}, 
        {"count": "15", "City": "Coral Springs", "State": "FL", "Attend": "7,826", "Church": "Church by the Glades"}, 
        {"count": "16", "City": "Corpus Christi", "State": "TX", "Attend": "7,600", "Church": "Bay Area Fellowship*"}, 
        {"count": "17", "City": "El Cajon", "State": "CA", "Attend": "7,432", "Church": "Shadow Mountain Community Church"}, 
        {"count": "18", "City": "Durham", "State": "NC", "Attend": "7,186", "Church": "The Summit Church-Homestead Heights"}, 
        {"count": "19", "City": "Stone Mountain", "State": "GA", "Attend": "6,900", "Church": "Voices of Faith Ministries"},
         {"count": "19", "City": "Atlanta", "State": "GA", "Attend": "6,900", "Church": "Elizabeth Baptist Church"}, 
         {"count": "21", "City": "Austin", "State": "TX", "Attend": "6,868", "Church": "The Austin Stone Community Church"}, 
         {"count": "22", "City": "Rialto", "State": "CA", "Attend": "6,830", "Church": "Sunrise Church*"}, 
         {"count": "23", "City": "Cordova", "State": "TN", "Attend": "6,801", "Church": "Bellevue Baptist Church"}, 
         {"count": "24", "City": "Woodstock", "State": "GA", "Attend": "6,371", "Church": "First Baptist of Woodstock"}, 
         {"count": "25", "City": "Arden", "State": "NC", "Attend": "6,054", "Church": "Biltmore"}, 
         {"count": "26", "City": "Wichita", "State": "KS", "Attend": "6,029", "Church": "Newspring Church"}, 
         {"count": "27", "City": "Lutz", "State": "FL", "Attend": "5,970", "Church": "Idlewild Baptist Church"}, 
         {"count": "28", "City": "Houston", "State": "TX", "Attend": "5,927", "Church": "Champion Forest Baptist Church"}, 
         {"count": "29", "City": "Brentwood", "State": "TN", "Attend": "5,865", "Church": "Brentwood Baptist Church"}, 
         {"count": "30", "City": "Dallas", "State": "TX", "Attend": "5,500", "Church": "Concord Missionary Baptist Church"}, 
         {"count": "30", "City": "Houston", "State": "TX", "Attend": "5,500", "Church": "Fallbrook Baptist Church"}, 
         {"count": "32", "City": "Houston", "State": "TX", "Attend": "5,325", "Church": "Houston\u2019s First Baptist Church"}, 
         {"count": "33", "City": "Knoxville", "State": "TN", "Attend": "5,254", "Church": "Faith Promise Church"}, 
         {"count": "34", "City": "Metairie", "State": "LA", "Attend": "5,233", "Church": "Celebration Church (SBC)"}, 
         {"count": "35", "City": "Riverside", "State": "CA", "Attend": "5,227", "Church": "Sandals Church"}, 
         {"count": "36", "City": "Orlando", "State": "FL", "Attend": "5,170", "Church": "First Baptist Church of Orlando"}, 
         {"count": "37", "City": "Bowling Green", "State": "KY", "Attend": "5,110", "Church": "Hillvue Heights Baptist Church"}, 
         {"count": "38", "City": "Greenville", "State": "SC", "Attend": "5,000", "Church": "Grace Church*"}, 
         {"count": "39", "City": "Atlanta", "State": "GA", "Attend": "4,918", "Church": "First Baptist of Atlanta"}, 
         {"count": "40", "City": "Houston", "State": "TX", "Attend": "4,783", "Church": "Sagemont Church"}, 
         {"count": "41", "City": "Tyler", "State": "TX", "Attend": "4,775", "Church": "Green Acres Baptist Church"}, 
         {"count": "42", "City": "Hampton", "State": "VA", "Attend": "4,773", "Church": "Liberty Baptist Church"}, 
         {"count": "43", "City": "Tampa", "State": "FL", "Attend": "4,613", "Church": "The Crossing Church"}, 
         {"count": "44", "City": "Jacksonville", "State": "FL", "Attend": "4,510", "Church": "First Baptist Church of Jacksonville, Florida, Inc"}, 
         {"count": "45", "City": "Richmond", "State": "TX", "Attend": "4,501", "Church": "River Pointe Community Church"}, 
         {"count": "46", "City": "League City", "State": "TX", "Attend": "4,500", "Church": "Clear Creek Community Church"}, 
         {"count": "47", "City": "Philadelphia", "State": "PA", "Attend": "4,494", "Church": "Sharon Baptist Church*"}, 
         {"count": "48", "City": "Tulsa", "State": "OK", "Attend": "4,318", "Church": "The Church at DuPage"}, 
         {"count": "49", "City": "New Orleans", "State": "LA", "Attend": "4,200", "Church": "Franklin Avenue Baptist Church"}, 
         {"count": "50", "City": "Little Rock", "State": "AR", "Attend": "4,100", "Church": "The Church at Rock Creek"} 
        ]);
    });
};
